### ISSUE TITLE
一直出现Invalid request!

### ISSUE THREAD

**Issue by josangmi** [bulianglin/psub#2]
Invalid request!

节点地址用的这个：
hysteria2://2U9sTl1u@102.165.15.21:8181,20000-50000/?insecure=1&sni=www.bing.com#Hysteria2

直接转是可以：
https://api.v1.mk/sub?target=clash&url=hysteria2%3A%2F%2F2U9sTl1u%40102.165.15.21%3A8181%2C20000-50000%2F%3Finsecure%3D1%26sni%3Dwww.bing.com%23Misaka-Hysteria2&insert=false&config=https%3A%2F%2Fraw.githubusercontent.com%2FACL4SSR%2FACL4SSR%2Fmaster%2FClash%2Fconfig%2FACL4SSR_Online_Full_NoAuto.ini&emoji=true&list=false&xudp=false&udp=false&tfo=false&expand=true&scv=false&fdn=false&new_name=true

<img width="550" alt="image" src="https://github.com/bulianglin/psub/assets/46701832/20b7ad82-fb4b-4b8d-9a8d-4ce6d2f3b09f">
变量也一样。 好奇怪会是

**Comment by bulianglin** [comment]
不支持hysteria2，实际上你也没有成功转换节点，只是输出了clash的模板

**Comment by Jacky-Bruse** [comment]
> 不支持hysteria2，实际上你也没有成功转换节点，只是输出了clash的模板

大佬，请问能否更新支持Hy2的，现在用肥羊转换hy2的会报如上错误，谢谢

**Comment by Cranberrycrisp** [comment]
我的订阅转换也一直Invalid request!，测试了ss和ssr协议都会。且最开始是好用的，多get几次就一直Invalid request!
