### ISSUE TITLE
IPV6解析存在问题

### ISSUE THREAD

**Issue by somnifex** [bulianglin/psub#3]
例如：server: XXXX:XXXX:XXXX:1e::, port: 12906, 因为server中最后为::导致yaml解析失败。对于::结尾地址应该用双引号解析，也就是：server: “XXXX:XXXX:XXXX:1e::”, port: 12906,

**Comment by bulianglin** [comment]
clash core可以正常解析，如果gui无法解析，可以在尾部加个0，比如XXXX:XXXX:XXXX:1e::0
