### ISSUE TITLE
自定义域名无法解析机场链接，使用*.worker.dev就能解析

### ISSUE THREAD

**Issue by coppea** [bulianglin/psub#5]
自定义域名提示无法找到node

**Comment by coppea** [comment]
删除重新安装就好了

**Comment by lainbo** [comment]
出现了相同的问题吗，能详细说说怎么解决的吗~

**Comment by coppea** [comment]
我看错了，还是不行，等修复吧

**Comment by bulianglin** [comment]
有些后端会屏蔽http的订阅链接，换个后端试试，或者你自己的域名改成https访问

**Comment by coppea** [comment]
我把sub.id9 v.id9 id9 都试了，还是不行

我自己的域名是https，机场订阅也是https，都不行

**Comment by lainbo** [comment]
> 我把sub.id9 v.id9 id9 都试了，还是不行
> 
> 我自己的域名是https，机场订阅也是https，都不行

我也是和你一样的清空，但是奇怪的是如果我用作者给的那个演示站就可以用(作者绑了自己域名的)

**Comment by bulianglin** [comment]
> 我把sub.id9 v.id9 id9 都试了，还是不行
> 
> 我自己的域名是https，机场订阅也是https，都不行

换别家的后端，再不行的话把详细发我邮箱，我看看

**Comment by m0eak** [comment]
我本来不行，后端地址把sub?去了就正常了

**Comment by coppea** [comment]
> 我本来不行，后端地址把sub?去了就正常了

是xxx.com/sub?target=clash&url=xxx   
是以上的sub地址吗，我去掉没反应
